apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ${ProjectName}
  namespace: ${Environment}
  labels:
    app.kubernetes.io/managed-by: Kaptain
    app.kubernetes.io/instance: ${ProjectName}
    app.kubernetes.io/version: "${Version}"
    kaptain.org/environment: ${Environment}
    kaptain.org/version: "${Version}"
    kaptain.org/project-name: ${ProjectName}
  annotations:
    app.kubernetes.io/managed-by: Kaptain
    app.kubernetes.io/version: "${Version}"
    kaptain.org/environment: ${Environment}
    kaptain.org/version: "${Version}"
    kaptain.org/project-name: ${ProjectName}
spec:
  gatewayClassName: ${VendorEnvoyGatewayProxy/GatewayClassName}
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: ${ProjectName}
  listeners:
    - name: ${VendorEnvoyGatewayProxy/ListenerName}
      protocol: ${VendorEnvoyGatewayProxy/ListenerProtocol}
      port: ${VendorEnvoyGatewayProxy/ListenerPort}
      tls:
        certificateRefs:
          - name: ${VendorEnvoyGatewayProxy/ListenerTlsCertificateName}
            namespace: ${Environment}
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values: [${VendorEnvoyGatewayProxy/ListenerAllowedRoutesNamespaces}]
